apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      name: mon-express
      labels:
        app: express
    spec:
      containers:
      - name: cont-express
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_BASICAUTH_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: ME_CONFIG_BASICAUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: myconfig
              key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: service-express
spec:
  selector:
    app: express
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30007

